version: "2.1"

services:

  jboss:
    build: .
    volumes: ["jboss-data:/home/app"]
    ports:
    - "5005:5005"
    - "8080:8080"
    - "9990:9990"
    networks: [backing-services]

volumes:
  jboss-data: {}

networks:
  backing-services:
    driver: bridge
