spring:
  datasource:
#    jndi-name: java:jboss/datasources/ExampleDS
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl.auto: create-drop
#        ##ejb.naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
#        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
  data:
    jpa:
      repositories:
        enabled: true
